Update README.md
vladdy-moses/ulstu-north-valley pull request #1
Opened 2022-05-23 19:49 UTC by Alex82ru73

Напоминалка о ссылке на чит-лист
Проба № 2. (с ожиданием ответа)

2022-05-23 19:51 UTC, Alex82ru73 commented
Жду ответа, как соловей лета)))

2022-05-24 09:17 UTC, vladdy-moses reviewed
Можете оформить её как ссылки выше? Если интересно, могу рассказать про такую разметку

2022-05-24 09:18 UTC, vladdy-moses requested changes
Оформите ссылку как предыдущие. :)

2022-05-24 18:56 UTC, vladdy-moses commented
Закрою, так как #3 исправляет этот

2022-05-24 18:56 UTC, closed without merging